# Data Scraping Basics

### Pandas Scraping HTML

In [1]:
import pandas as pd
import requests

In [2]:
# fbref table link
url_df = 'https://fbref.com/en/comps/Big5/gca/players/Big-5-European-Leagues-Stats#stats_gca'

# Disable SSL verification and fetch the HTML content
response = requests.get(url_df, verify=False)
df = pd.read_html(response.text)[0]
df.head()

/Users/miwebo/Desktop/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'fbref.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/var/folders/2l/98dn0dvj6jx4l166nprz2mc00000gn/T/ipykernel_20474/2932995248.py:6: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(response.text)[0]

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                  Rk             Player             Nation                Pos
0                  1         Max Aarons            eng ENG                 DF
1                  2         Max Aarons            eng ENG                 MF
2                  3     Rodrigo Abajas             es ESP                 DF
3                  4     James Abankwah             ie IRL              DF,MF
4                  5  Keyliane Abdallah             fr FRA                 FW

  Unnamed: 4_level_0  Unnamed: 5_level_0 Unnamed: 6_level_0  \
               Squad                Comp                Age
0        Bournemouth  eng Premier League             25-061
1           Valencia          es La Liga             25-061
2           Valencia          es La Liga             21-298
3            Udinese          it Serie A             21-049
4          Marseille          fr Ligue 1             18-335

  Unnamed: 7_level_0 Unnamed: 8_level_0 SCA  ... SCA Types GCA        \
                Born                90s SCA  ...       Def GCA GCA90
0               2000                1.0   2  ...         0   0  0.00
1               2000                0.3   0  ...         0   0  0.00
2               2003                0.7   0  ...         0   0  0.00
3               2004                1.0   1  ...         0   0  0.00
4               2006                0.0   0  ...         0   0  0.00

  GCA Types                        Unnamed: 25_level_0
   PassLive PassDead TO Sh Fld Def             Matches
0         0        0  0  0   0   0             Matches
1         0        0  0  0   0   0             Matches
2         0        0  0  0   0   0             Matches
3         0        0  0  0   0   0             Matches
4         0        0  0  0   0   0             Matches

[5 rows x 26 columns]

In [3]:
df.columns = [' '.join(col).strip() for col in df.columns]

df = df.reset_index(drop=True)
df.head()

,Unnamed: 0_level_0 Rk,Unnamed: 1_level_0 Player,Unnamed: 2_level_0 Nation,Unnamed: 3_level_0 Pos,Unnamed: 4_level_0 Squad,Unnamed: 5_level_0 Comp,Unnamed: 6_level_0 Age,Unnamed: 7_level_0 Born,Unnamed: 8_level_0 90s,SCA SCA,...,SCA Types Def,GCA GCA,GCA GCA90,GCA Types PassLive,GCA Types PassDead,GCA Types TO,GCA Types Sh,GCA Types Fld,GCA Types Def,Unnamed: 25_level_0 Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,25-061,2000,1.0,2,...,0,0,0.00,0,0,0,0,0,0,Matches
1,2,Max Aarons,eng ENG,MF,Valencia,es La Liga,25-061,2000,0.3,0,...,0,0,0.00,0,0,0,0,0,0,Matches
2,3,Rodrigo Abajas,es ESP,DF,Valencia,es La Liga,21-298,2003,0.7,0,...,0,0,0.00,0,0,0,0,0,0,Matches
3,4,James Abankwah,ie IRL,"DF,MF",Udinese,it Serie A,21-049,2004,1.0,1,...,0,0,0.00,0,0,0,0,0,0,Matches
4,5,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,18-335,2006,0.0,0,...,0,0,0.00,0,0,0,0,0,0,Matches

In [4]:
# creating a list with new names
new_columns = []
for col in df.columns:
  if 'level_0' in col:
      new_col = col.split()[-1]  # takes the last name
  else:
      new_col = col
  new_columns.append(new_col)

# rename columns
df.columns = new_columns
df = df.fillna(0)

df.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,SCA SCA,...,SCA Types Def,GCA GCA,GCA GCA90,GCA Types PassLive,GCA Types PassDead,GCA Types TO,GCA Types Sh,GCA Types Fld,GCA Types Def,Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,25-061,2000,1.0,2,...,0,0,0.00,0,0,0,0,0,0,Matches
1,2,Max Aarons,eng ENG,MF,Valencia,es La Liga,25-061,2000,0.3,0,...,0,0,0.00,0,0,0,0,0,0,Matches
2,3,Rodrigo Abajas,es ESP,DF,Valencia,es La Liga,21-298,2003,0.7,0,...,0,0,0.00,0,0,0,0,0,0,Matches
3,4,James Abankwah,ie IRL,"DF,MF",Udinese,it Serie A,21-049,2004,1.0,1,...,0,0,0.00,0,0,0,0,0,0,Matches
4,5,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,18-335,2006,0.0,0,...,0,0,0.00,0,0,0,0,0,0,Matches

In [5]:
df.dropna(subset=['Rk'], inplace=True)

In [6]:
url = 'https://fbref.com/en/squads/19538871/Manchester-United-Stats'
response = requests.get(url)
df = pd.read_html(response.text, attrs={"id": "stats_standard_9"})[0]

/var/folders/2l/98dn0dvj6jx4l166nprz2mc00000gn/T/ipykernel_20474/70844999.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(response.text, attrs={"id": "stats_standard_9"})[0]

In [7]:
df.columns = df.columns.get_level_values(1)
df.columns = df.columns.str.replace(' ', '_')
df.head()

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,Ast,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG,Matches
0,André Onana,cm CMR,GK,28-338,27,27,2430.0,27.0,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.00,0.01,Matches
1,Diogo Dalot,pt POR,DF,25-353,26,26,2306.0,25.6,0.0,1.0,...,0.04,0.04,0.00,0.04,0.07,0.06,0.13,0.07,0.13,Matches
2,Bruno Fernandes,pt POR,MF,30-179,26,26,2195.0,24.4,6.0,7.0,...,0.29,0.53,0.12,0.41,0.33,0.23,0.56,0.23,0.46,Matches
3,Noussair Mazraoui,ma MAR,DF,27-112,27,24,2038.0,22.6,0.0,1.0,...,0.04,0.04,0.00,0.04,0.02,0.04,0.06,0.02,0.06,Matches
4,Matthijs de Ligt,nl NED,DF,25-206,25,21,1819.0,20.2,2.0,0.0,...,0.00,0.10,0.10,0.10,0.11,0.02,0.13,0.11,0.13,Matches

### SoccerData Scraping

In [8]:
import soccerdata as sd

[03/06/25 04:46:09] INFO     No custom team name replacements found. You can configure these in       ]8;id=213105;file:///Users/miwebo/Desktop/venv/lib/python3.12/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=422634;file:///Users/miwebo/Desktop/venv/lib/python3.12/site-packages/soccerdata/_config.py#91\91]8;;\
                             /Users/miwebo/soccerdata/config/teamname_replacements.json.

                    INFO     No custom league dict found. You can configure additional leagues in    ]8;id=713607;file:///Users/miwebo/Desktop/venv/lib/python3.12/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=103386;file:///Users/miwebo/Desktop/venv/lib/python3.12/site-packages/soccerdata/_config.py#197\197]8;;\
                             /Users/miwebo/soccerdata/config/league_dict.json.

### FBRef

In [9]:
fbref = sd.FBref(leagues="ENG-Premier League", seasons=2021)
print(fbref.__doc__)

[03/06/25 04:46:13] INFO     Saving cached data to /Users/miwebo/soccerdata/data/FBref               ]8;id=34906;file:///Users/miwebo/Desktop/venv/lib/python3.12/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=567792;file:///Users/miwebo/Desktop/venv/lib/python3.12/site-packages/soccerdata/_common.py#263\263]8;;\

                    WARNING  /Users/miwebo/Desktop/venv/lib/python3.12/site-packages/soccerdata/_co ]8;id=114220;file:///Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/warnings.py\warnings.py]8;;\:]8;id=149123;file:///Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/warnings.py#112\112]8;;\
                             mmon.py:145: UserWarning: Season id "2021" is ambiguous: interpreting
                             as "20-21"
                               warnings.warn(msg, stacklevel=1)

Provides pd.DataFrames from data at http://fbref.com.

    Data will be downloaded as necessary and cached locally in
    ``~/soccerdata/data/FBref``.

    Parameters
    ----------
    leagues : string or iterable, optional
        IDs of leagues to include. For efficiently reading data from the Top-5
        European leagues, use "Big 5 European Leagues Combined".
    seasons : string, int or list, optional
        Seasons to include. Supports multiple formats.
        Examples: '16-17'; 2016; '2016-17'; [14, 15, 16]
    proxy : 'tor' or dict or list(dict) or callable, optional
        Use a proxy to hide your IP address. Valid options are:
            - "tor": Uses the Tor network. Tor should be running in
              the background on port 9050.
            - dict: A dictionary with the proxy to use. The dict should be
              a mapping of supported protocols to proxy addresses. For example::

                  {
                      'http': 'http://10.10.1.10:3128',
                      'https': 'http://10.10.1.10:1080',
                  }

            - list(dict): A list of proxies to choose from. A different proxy will
              be selected from this list after failed requests, allowing rotating
              proxies.
            - callable: A function that returns a valid proxy. This function will
              be called after failed requests, allowing rotating proxies.
    no_cache : bool
        If True, will not use cached data.
    no_store : bool
        If True, will not store downloaded data.
    data_dir : Path
        Path to directory where data will be cached.

In [21]:
team_season_stats = fbref.read_team_season_stats(stat_type="passing")
team_season_stats.head()

[03/06/25 04:51:21] WARNING  /Users/miwebo/Desktop/venv/lib/python3.12/site-packages/soccerdata/fbr ]8;id=695681;file:///Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/warnings.py\warnings.py]8;;\:]8;id=257653;file:///Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/warnings.py#112\112]8;;\
                             ef.py:165: FutureWarning: The behavior of DataFrame concatenation with
                             empty or all-NA entries is deprecated. In a future version, this will
                             no longer exclude empty or all-NA columns when determining the result
                             dtypes. To retain the old behavior, exclude the relevant entries
                             before the concat operation.
                               pd.concat(dfs)

                                      players_used 90s  Total               \
                                                          Cmp    Att  Cmp%
league             season team
ENG-Premier League 2021   Arsenal               29  38  18041  21807  82.7
                          Aston Villa           24  38  12938  16996  76.1
                          Brighton              27  38  15772  19871  79.4
                          Burnley               25  38  10825  15562  69.6
                          Chelsea               27  38  21969  25799  85.2

                                                       Short               \
                                      TotDist PrgDist    Cmp    Att  Cmp%
league             season team
ENG-Premier League 2021   Arsenal      306094   93540   8319   9236  90.1
                          Aston Villa  235927   93009   5729   6654  86.1
                          Brighton     283213   95248   6694   7654  87.5
                          Burnley      196816   82192   5117   6058  84.5
                          Chelsea      360450  112392  10454  11454  91.3

                                       ... Ast   xAG Expected         KP  \
                                       ...                 xA A-xAG
league             season team         ...
ENG-Premier League 2021   Arsenal      ...  38  35.1     35.3   2.9  332
                          Aston Villa  ...  38  37.4     31.4   0.6  403
                          Brighton     ...  24  33.2     34.9  -9.2  358
                          Burnley      ...  20  27.7     26.9  -7.7  267
                          Chelsea      ...  38  41.5     37.1  -3.5  448

                                        1/3  PPA CrsPA  PrgP  \

league             season team
ENG-Premier League 2021   Arsenal      1377  325    67  1760
                          Aston Villa  1086  323    76  1420
                          Brighton     1132  358    80  1516
                          Burnley       923  292    80  1012
                          Chelsea      1441  377    70  1798

                                                                                     url

league             season team
ENG-Premier League 2021   Arsenal            /en/squads/18bb7c10/2020-2021/Arsenal-Stats
                          Aston Villa    /en/squads/8602292d/2020-2021/Aston-Villa-Stats
                          Brighton     /en/squads/d07537b9/2020-2021/Brighton-and-Hov...
                          Burnley            /en/squads/943e8050/2020-2021/Burnley-Stats
                          Chelsea            /en/squads/cff3d9bb/2020-2021/Chelsea-Stats

[5 rows x 26 columns]

In [16]:
player_season_stats = fbref.read_player_season_stats(stat_type="standard")
player_season_stats.head()

[03/06/25 04:50:14] WARNING  /Users/miwebo/Desktop/venv/lib/python3.12/site-packages/soccerdata/fbr ]8;id=205696;file:///Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/warnings.py\warnings.py]8;;\:]8;id=639422;file:///Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/warnings.py#112\112]8;;\
                             ef.py:165: FutureWarning: The behavior of DataFrame concatenation with
                             empty or all-NA entries is deprecated. In a future version, this will
                             no longer exclude empty or all-NA columns when determining the result
                             dtypes. To retain the old behavior, exclude the relevant entries
                             before the concat operation.
                               pd.concat(dfs)

                                                         nation    pos age  \

league             season team    player
ENG-Premier League 2021   Arsenal Ainsley Maitland-Niles    ENG  MF,DF  22
                                  Alexandre Lacazette       FRA     FW  29
                                  Bernd Leno                GER     GK  28
                                  Bukayo Saka               ENG  FW,MF  18
                                  Calum Chambers            ENG     DF  25

                                                          born Playing Time  \
                                                                         MP
league             season team    player
ENG-Premier League 2021   Arsenal Ainsley Maitland-Niles  1997           11
                                  Alexandre Lacazette     1991           31
                                  Bernd Leno              1992           35
                                  Bukayo Saka             2001           32
                                  Calum Chambers          1995           10

                                                                             \
                                                         Starts   Min   90s
league             season team    player
ENG-Premier League 2021   Arsenal Ainsley Maitland-Niles      5   490   5.4
                                  Alexandre Lacazette        22  1923  21.4
                                  Bernd Leno                 35  3131  34.8
                                  Bukayo Saka                30  2553  28.4
                                  Calum Chambers              8   753   8.4

                                                         Performance      ...  \
                                                                 Gls Ast  ...
league             season team    player                                  ...
ENG-Premier League 2021   Arsenal Ainsley Maitland-Niles           0   0  ...
                                  Alexandre Lacazette             13   2  ...
                                  Bernd Leno                       0   0  ...
                                  Bukayo Saka                      5   3  ...
                                  Calum Chambers                   0   2  ...

                                                         Per 90 Minutes        \
                                                                    Gls   Ast
league             season team    player
ENG-Premier League 2021   Arsenal Ainsley Maitland-Niles            0.0   0.0
                                  Alexandre Lacazette              0.61  0.09
                                  Bernd Leno                        0.0   0.0
                                  Bukayo Saka                      0.18  0.11
                                  Calum Chambers                    0.0  0.24

                                                                             \
                                                           G+A  G-PK G+A-PK
league             season team    player
ENG-Premier League 2021   Arsenal Ainsley Maitland-Niles   0.0   0.0    0.0
                                  Alexandre Lacazette      0.7  0.47   0.56
                                  Bernd Leno               0.0   0.0    0.0
                                  Bukayo Saka             0.28  0.18   0.28
                                  Calum Chambers          0.24   0.0   0.24

                                                                             \
                                                            xG   xAG xG+xAG
league             season team    player
ENG-Premier League 2021   Arsenal Ainsley Maitland-Niles  0.01  0.02   0.04
                                  Alexandre Lacazette     0.55   0.1   0.65
                                  Bernd Leno               0.0   0.0    0.0
                                  Bukayo Saka             0.24  0.16    0.4
                                  Calum Chambers          0.05  0.13   0.18


                                                          npxG npxG+xAG
league             season team    player
ENG-Premier League 2021   Arsenal Ainsley Maitland-Niles  0.01     0.04
                                  Alexandre Lacazette     0.43     0.54
                                  Bernd Leno               0.0      0.0
                                  Bukayo Saka             0.24      0.4
                                  Calum Chambers          0.05     0.18

[5 rows x 33 columns]

In [18]:
player_match_stats = fbref.read_player_match_stats(stat_type="passing", match_id='db261cb0')
player_match_stats.head()

[03/06/25 04:50:32] WARNING  /Users/miwebo/Desktop/venv/lib/python3.12/site-packages/soccerdata/fbr ]8;id=11202;file:///Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/warnings.py\warnings.py]8;;\:]8;id=953682;file:///Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/warnings.py#112\112]8;;\
                             ef.py:165: FutureWarning: The behavior of DataFrame concatenation with
                             empty or all-NA entries is deprecated. In a future version, this will
                             no longer exclude empty or all-NA columns when determining the result
                             dtypes. To retain the old behavior, exclude the relevant entries
                             before the concat operation.
                               pd.concat(dfs)

[03/06/25 04:50:45] INFO     [1/1] Retrieving game with id=db261cb0                                    ]8;id=839783;file:///Users/miwebo/Desktop/venv/lib/python3.12/site-packages/soccerdata/fbref.py\fbref.py]8;;\:]8;id=718408;file:///Users/miwebo/Desktop/venv/lib/python3.12/site-packages/soccerdata/fbref.py#815\815]8;;\

                                                                                                jersey_number  \

league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend             10
                                                                               Cheikhou Kouyaté             8
                                                                               Eberechi Eze                25
                                                                               James McArthur              18
                                                                               James McCarthy              22

                                                                                                nation  \

league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend     ENG
                                                                               Cheikhou Kouyaté    SEN
                                                                               Eberechi Eze        ENG
                                                                               James McArthur      SCO
                                                                               James McCarthy      IRL

                                                                                                pos  \

league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend   RM
                                                                               Cheikhou Kouyaté  CB
                                                                               Eberechi Eze      LM
                                                                               James McArthur    CM
                                                                               James McCarthy    CM

                                                                                                    age  \

league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend   29-058
                                                                               Cheikhou Kouyaté  30-266
                                                                               Eberechi Eze      22-075
                                                                               James McArthur    32-341
                                                                               James McCarthy    29-305

                                                                                                min  \

league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend   90
                                                                               Cheikhou Kouyaté  90
                                                                               Eberechi Eze      10
                                                                               James McArthur    90
                                                                               James McCarthy    73

                                                                                                Total  \
                                                                                                  Cmp
league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend     13
                                                                               Cheikhou Kouyaté    11
                                                                               Eberechi Eze         8
                                                                               James McArthur      15
                                                                               James McCarthy      14

                                                                                                     \
                                                                                                Att
league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend   30
                                                                               Cheikhou Kouyaté  19
                                                                               Eberechi Eze      10
                                                                               James McArthur    32
                                                                               James McCarthy    23

                                                                                                       \
                                                                                                 Cmp%
league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend   43.3
                                                                               Cheikhou Kouyaté  57.9
                                                                               Eberechi Eze      80.0
                                                                               James McArthur    46.9
                                                                               James McCarthy    60.9

                                                                                                         \
                                                                                                TotDist
league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend      184
                                                                               Cheikhou Kouyaté     207
                                                                               Eberechi Eze         177
                                                                               James McArthur       322
                                                                               James McCarthy       281

                                                                                                         \
                                                                                                PrgDist
league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend       68
                                                                               Cheikhou Kouyaté     109
                                                                               Eberechi Eze          46
                                                                               James McArthur       159
                                                                               James McCarthy        75

                                                                                                 ...  \
                                                                                                 ...
league             season game                                  team           player            ...
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend   ...
                                                                               Cheikhou Kouyaté  ...
                                                                               Eberechi Eze      ...
                                                                               James McArthur    ...
                                                                               James McCarthy    ...

                                                                                                 Long  \
                                                                                                 Cmp%
league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend   16.7
                                                                               Cheikhou Kouyaté  50.0
                                                                               Eberechi Eze      66.7
                                                                               James McArthur    14.3
                                                                               James McCarthy    60.0

                                                                                                Ast  \

league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend    1
                                                                               Cheikhou Kouyaté   0
                                                                               Eberechi Eze       0
                                                                               James McArthur     0
                                                                               James McCarthy     0

                                                                                                 xAG  \

league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend   0.6
                                                                               Cheikhou Kouyaté  0.0
                                                                               Eberechi Eze      0.0
                                                                               James McArthur    0.4
                                                                               James McCarthy    0.0

                                                                                                  xA  \

league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend   0.2
                                                                               Cheikhou Kouyaté  0.0
                                                                               Eberechi Eze      0.0
                                                                               James McArthur    0.0
                                                                               James McCarthy    0.1

                                                                                                KP  \

league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend   2
                                                                               Cheikhou Kouyaté  0
                                                                               Eberechi Eze      0
                                                                               James McArthur    1
                                                                               James McCarthy    0

                                                                                                1/3  \

league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend    0
                                                                               Cheikhou Kouyaté   1
                                                                               Eberechi Eze       1
                                                                               James McArthur     2
                                                                               James McCarthy     0

                                                                                                PPA  \

league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend    1
                                                                               Cheikhou Kouyaté   0
                                                                               Eberechi Eze       0
                                                                               James McArthur     0
                                                                               James McCarthy     0

                                                                                                CrsPA  \

league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend      0
                                                                               Cheikhou Kouyaté     0
                                                                               Eberechi Eze         0
                                                                               James McArthur       0
                                                                               James McCarthy       0

                                                                                                PrgP  \

league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend     1
                                                                               Cheikhou Kouyaté    2
                                                                               Eberechi Eze        2
                                                                               James McArthur      3
                                                                               James McCarthy      2

                                                                                                  game_id

league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend   db261cb0
                                                                               Cheikhou Kouyaté  db261cb0
                                                                               Eberechi Eze      db261cb0
                                                                               James McArthur    db261cb0
                                                                               James McCarthy    db261cb0

[5 rows x 28 columns]

In [23]:
events = fbref.read_events(match_id='db261cb0')
events.head()

[03/06/25 04:51:46] WARNING  /Users/miwebo/Desktop/venv/lib/python3.12/site-packages/soccerdata/fbr ]8;id=433971;file:///Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/warnings.py\warnings.py]8;;\:]8;id=499019;file:///Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/warnings.py#112\112]8;;\
                             ef.py:165: FutureWarning: The behavior of DataFrame concatenation with
                             empty or all-NA entries is deprecated. In a future version, this will
                             no longer exclude empty or all-NA columns when determining the result
                             dtypes. To retain the old behavior, exclude the relevant entries
                             before the concat operation.
                               pd.concat(dfs)

                    INFO     [1/1] Retrieving game with id=db261cb0                                    ]8;id=593268;file:///Users/miwebo/Desktop/venv/lib/python3.12/site-packages/soccerdata/fbref.py\fbref.py]8;;\:]8;id=912786;file:///Users/miwebo/Desktop/venv/lib/python3.12/site-packages/soccerdata/fbref.py#999\999]8;;\

                                                                           team  \
league             season game
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton  Crystal Palace
                          2020-09-12 Crystal Palace-Southampton  Crystal Palace
                          2020-09-12 Crystal Palace-Southampton     Southampton
                          2020-09-12 Crystal Palace-Southampton     Southampton
                          2020-09-12 Crystal Palace-Southampton  Crystal Palace

                                                                minute score  \
league             season game
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton     13   1:0
                          2020-09-12 Crystal Palace-Southampton     41   1:0
                          2020-09-12 Crystal Palace-Southampton     46   1:0
                          2020-09-12 Crystal Palace-Southampton     51   1:0
                          2020-09-12 Crystal Palace-Southampton     58   1:0

                                                                            player1  \
league             season game
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton       Wilfried Zaha
                          2020-09-12 Crystal Palace-Southampton     Jeffrey Schlupp
                          2020-09-12 Crystal Palace-Southampton  Jannik Vestergaard
                          2020-09-12 Crystal Palace-Southampton  Kyle Walker-Peters
                          2020-09-12 Crystal Palace-Southampton      James McCarthy

                                                                         player2  \
league             season game
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton  Andros Townsend
                          2020-09-12 Crystal Palace-Southampton             None
                          2020-09-12 Crystal Palace-Southampton     Jan Bednarek
                          2020-09-12 Crystal Palace-Southampton             None
                          2020-09-12 Crystal Palace-Southampton             None

                                                                    event_type
league             season game
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton           goal
                          2020-09-12 Crystal Palace-Southampton    yellow_card
                          2020-09-12 Crystal Palace-Southampton  substitute_in
                          2020-09-12 Crystal Palace-Southampton    yellow_card
                          2020-09-12 Crystal Palace-Southampton    yellow_card

In [24]:
shots = fbref.read_shot_events(match_id='db261cb0')
shots.head()

[03/06/25 04:52:07] WARNING  /Users/miwebo/Desktop/venv/lib/python3.12/site-packages/soccerdata/fbr ]8;id=262440;file:///Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/warnings.py\warnings.py]8;;\:]8;id=201924;file:///Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/warnings.py#112\112]8;;\
                             ef.py:165: FutureWarning: The behavior of DataFrame concatenation with
                             empty or all-NA entries is deprecated. In a future version, this will
                             no longer exclude empty or all-NA columns when determining the result
                             dtypes. To retain the old behavior, exclude the relevant entries
                             before the concat operation.
                               pd.concat(dfs)

                    INFO     [1/1] Retrieving game with id=db261cb0                                   ]8;id=286755;file:///Users/miwebo/Desktop/venv/lib/python3.12/site-packages/soccerdata/fbref.py\fbref.py]8;;\:]8;id=304017;file:///Users/miwebo/Desktop/venv/lib/python3.12/site-packages/soccerdata/fbref.py#1098\1098]8;;\

                                                                minute  \

league             season game
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton      4
                          2020-09-12 Crystal Palace-Southampton     13
                          2020-09-12 Crystal Palace-Southampton     32
                          2020-09-12 Crystal Palace-Southampton     36
                          2020-09-12 Crystal Palace-Southampton     46

                                                                           player  \

league             season game
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton     Jack Stephens
                          2020-09-12 Crystal Palace-Southampton     Wilfried Zaha
                          2020-09-12 Crystal Palace-Southampton        Danny Ings
                          2020-09-12 Crystal Palace-Southampton  Cheikhou Kouyaté
                          2020-09-12 Crystal Palace-Southampton    Nathan Redmond

                                                                           team  \

league             season game
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton     Southampton
                          2020-09-12 Crystal Palace-Southampton  Crystal Palace
                          2020-09-12 Crystal Palace-Southampton     Southampton
                          2020-09-12 Crystal Palace-Southampton  Crystal Palace
                          2020-09-12 Crystal Palace-Southampton     Southampton

                                                                   xG  PSxG  \

league             season game
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton  0.07  0.09
                          2020-09-12 Crystal Palace-Southampton  0.44  0.73
                          2020-09-12 Crystal Palace-Southampton  0.04  0.12
                          2020-09-12 Crystal Palace-Southampton  0.15  0.09
                          2020-09-12 Crystal Palace-Southampton  0.07  0.03

                                                                outcome  \

league             season game
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton   Saved
                          2020-09-12 Crystal Palace-Southampton    Goal
                          2020-09-12 Crystal Palace-Southampton   Saved
                          2020-09-12 Crystal Palace-Southampton   Saved
                          2020-09-12 Crystal Palace-Southampton   Saved

                                                                distance  \

league             season game
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton       10
                          2020-09-12 Crystal Palace-Southampton        9
                          2020-09-12 Crystal Palace-Southampton       10
                          2020-09-12 Crystal Palace-Southampton       11
                          2020-09-12 Crystal Palace-Southampton       14

                                                                  body_part  \

league             season game
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton        Head
                          2020-09-12 Crystal Palace-Southampton  Right Foot
                          2020-09-12 Crystal Palace-Southampton        Head
                          2020-09-12 Crystal Palace-Southampton  Right Foot
                          2020-09-12 Crystal Palace-Southampton  Right Foot

                                                                  notes  \

league             season game
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton    <NA>
                          2020-09-12 Crystal Palace-Southampton  Volley
                          2020-09-12 Crystal Palace-Southampton    <NA>
                          2020-09-12 Crystal Palace-Southampton    <NA>
                          2020-09-12 Crystal Palace-Southampton    <NA>

                                                                              SCA 1  \
                                                                             player
league             season game
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton   James Ward-Prowse
                          2020-09-12 Crystal Palace-Southampton     Andros Townsend
                          2020-09-12 Crystal Palace-Southampton  Kyle Walker-Peters
                          2020-09-12 Crystal Palace-Southampton     Andros Townsend
                          2020-09-12 Crystal Palace-Southampton           Che Adams

                                                                              \
                                                                       event
league             season game
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton  Pass (Dead)
                          2020-09-12 Crystal Palace-Southampton  Pass (Live)
                          2020-09-12 Crystal Palace-Southampton  Pass (Live)
                          2020-09-12 Crystal Palace-Southampton  Pass (Dead)
                          2020-09-12 Crystal Palace-Southampton  Pass (Live)

                                                                              SCA 2  \
                                                                             player
league             season game
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton  Kyle Walker-Peters
                          2020-09-12 Crystal Palace-Southampton      James McCarthy
                          2020-09-12 Crystal Palace-Southampton   William Smallbone
                          2020-09-12 Crystal Palace-Southampton       Wilfried Zaha
                          2020-09-12 Crystal Palace-Southampton          Danny Ings


                                                                        event
league             season game
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton   Pass (Dead)
                          2020-09-12 Crystal Palace-Southampton  Interception
                          2020-09-12 Crystal Palace-Southampton   Pass (Live)
                          2020-09-12 Crystal Palace-Southampton        Fouled
                          2020-09-12 Crystal Palace-Southampton   Pass (Live)

### Understat

In [25]:
understat = sd.Understat(leagues="ENG-Premier League", seasons="2024/2025")
print(understat.__doc__)

[03/06/25 04:52:13] INFO     Saving cached data to /Users/miwebo/soccerdata/data/Understat           ]8;id=75859;file:///Users/miwebo/Desktop/venv/lib/python3.12/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=310464;file:///Users/miwebo/Desktop/venv/lib/python3.12/site-packages/soccerdata/_common.py#263\263]8;;\

Provides pd.DataFrames from data at https://understat.com.

    Data will be downloaded as necessary and cached locally in
    ``~/soccerdata/data/Understat``.

    Parameters
    ----------
    proxy : 'tor' or dict or list(dict) or callable, optional
        Use a proxy to hide your IP address. Valid options are:
            - "tor": Uses the Tor network. Tor should be running in
              the background on port 9050.
            - dict: A dictionary with the proxy to use. The dict should be
              a mapping of supported protocols to proxy addresses. For example::

                  {
                      'http': 'http://10.10.1.10:3128',
                      'https': 'http://10.10.1.10:1080',
                  }

            - list(dict): A list of proxies to choose from. A different proxy will
              be selected from this list after failed requests, allowing rotating
              proxies.
            - callable: A function that returns a valid proxy. This function will
              be called after failed requests, allowing rotating proxies.
    no_cache : bool
        If True, will not use cached data.
    no_store : bool
        If True, will not store downloaded data.
    data_dir : Path
        Path to directory where data will be cached.

In [26]:
team_match_stats = understat.read_team_match_stats()
team_match_stats.head()

                                                                     league_id  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                1
                          2024-08-17 Arsenal-Wolverhampton Wanderers         1
                          2024-08-17 Everton-Brighton                        1
                          2024-08-17 Ipswich-Liverpool                       1
                          2024-08-17 Newcastle United-Southampton            1

                                                                      season_id  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham              2024
                          2024-08-17 Arsenal-Wolverhampton Wanderers       2024
                          2024-08-17 Everton-Brighton                      2024
                          2024-08-17 Ipswich-Liverpool                     2024
                          2024-08-17 Newcastle United-Southampton          2024

                                                                      game_id  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham           26602
                          2024-08-17 Arsenal-Wolverhampton Wanderers    26604
                          2024-08-17 Everton-Brighton                   26605
                          2024-08-17 Ipswich-Liverpool                  26603
                          2024-08-17 Newcastle United-Southampton       26606

                                                                                    date  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham        2024-08-16 19:00:00
                          2024-08-17 Arsenal-Wolverhampton Wanderers 2024-08-17 14:00:00
                          2024-08-17 Everton-Brighton                2024-08-17 14:00:00
                          2024-08-17 Ipswich-Liverpool               2024-08-17 11:30:00
                          2024-08-17 Newcastle United-Southampton    2024-08-17 14:00:00

                                                                      home_team_id  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                   89
                          2024-08-17 Arsenal-Wolverhampton Wanderers            83
                          2024-08-17 Everton-Brighton                           72
                          2024-08-17 Ipswich-Liverpool                         285
                          2024-08-17 Newcastle United-Southampton               86

                                                                      away_team_id  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                  228
                          2024-08-17 Arsenal-Wolverhampton Wanderers           229
                          2024-08-17 Everton-Brighton                          220
                          2024-08-17 Ipswich-Liverpool                          87
                          2024-08-17 Newcastle United-Southampton               74

                                                                              home_team  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham         Manchester United
                          2024-08-17 Arsenal-Wolverhampton Wanderers            Arsenal
                          2024-08-17 Everton-Brighton                           Everton
                          2024-08-17 Ipswich-Liverpool                          Ipswich
                          2024-08-17 Newcastle United-Southampton      Newcastle United

                                                                                    away_team  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                          Fulham
                          2024-08-17 Arsenal-Wolverhampton Wanderers  Wolverhampton Wanderers
                          2024-08-17 Everton-Brighton                                Brighton
                          2024-08-17 Ipswich-Liverpool                              Liverpool
                          2024-08-17 Newcastle United-Southampton                 Southampton

                                                                     away_team_code  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                   FLH
                          2024-08-17 Arsenal-Wolverhampton Wanderers            WOL
                          2024-08-17 Everton-Brighton                           BRI
                          2024-08-17 Ipswich-Liverpool                          LIV
                          2024-08-17 Newcastle United-Southampton               SOU

                                                                     home_team_code  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                   MUN
                          2024-08-17 Arsenal-Wolverhampton Wanderers            ARS
                          2024-08-17 Everton-Brighton                           EVE
                          2024-08-17 Ipswich-Liverpool                          IPS
                          2024-08-17 Newcastle United-Southampton               NEW

                                                                      ...  \
league             season game                                        ...
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham         ...
                          2024-08-17 Arsenal-Wolverhampton Wanderers  ...
                          2024-08-17 Everton-Brighton                 ...
                          2024-08-17 Ipswich-Liverpool                ...
                          2024-08-17 Newcastle United-Southampton     ...

                                                                      away_ppda  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham         10.833333
                          2024-08-17 Arsenal-Wolverhampton Wanderers  10.818182
                          2024-08-17 Everton-Brighton                  7.916667
                          2024-08-17 Ipswich-Liverpool                  8.73913
                          2024-08-17 Newcastle United-Southampton      3.789474

                                                                      away_deep_completions  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                             3
                          2024-08-17 Arsenal-Wolverhampton Wanderers                      2
                          2024-08-17 Everton-Brighton                                     5
                          2024-08-17 Ipswich-Liverpool                                   13
                          2024-08-17 Newcastle United-Southampton                        13

                                                                      home_points  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                   3
                          2024-08-17 Arsenal-Wolverhampton Wanderers            3
                          2024-08-17 Everton-Brighton                           0
                          2024-08-17 Ipswich-Liverpool                          0
                          2024-08-17 Newcastle United-Southampton               3

                                                                      home_expected_points  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                       2.5696
                          2024-08-17 Arsenal-Wolverhampton Wanderers                2.1894
                          2024-08-17 Everton-Brighton                               0.3078
                          2024-08-17 Ipswich-Liverpool                              0.0258
                          2024-08-17 Newcastle United-Southampton                   0.2774

                                                                      home_goals  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                  1
                          2024-08-17 Arsenal-Wolverhampton Wanderers           2
                          2024-08-17 Everton-Brighton                          0
                          2024-08-17 Ipswich-Liverpool                         0
                          2024-08-17 Newcastle United-Southampton              1

                                                                       home_xg  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham          2.04268
                          2024-08-17 Arsenal-Wolverhampton Wanderers    1.6283
                          2024-08-17 Everton-Brighton                 0.405325
                          2024-08-17 Ipswich-Liverpool                0.342601
                          2024-08-17 Newcastle United-Southampton     0.433489

                                                                      home_np_xg  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham            2.04268
                          2024-08-17 Arsenal-Wolverhampton Wanderers      1.6283
                          2024-08-17 Everton-Brighton                   0.405325
                          2024-08-17 Ipswich-Liverpool                  0.342601
                          2024-08-17 Newcastle United-Southampton       0.433489

                                                                      home_np_xg_difference  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                      1.623969
                          2024-08-17 Arsenal-Wolverhampton Wanderers               1.052465
                          2024-08-17 Everton-Brighton                             -1.385505
                          2024-08-17 Ipswich-Liverpool                            -3.586459
                          2024-08-17 Newcastle United-Southampton                 -1.521341

                                                                      home_ppda  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham           7.37931
                          2024-08-17 Arsenal-Wolverhampton Wanderers   7.769231
                          2024-08-17 Everton-Brighton                 18.333333
                          2024-08-17 Ipswich-Liverpool                18.777778
                          2024-08-17 Newcastle United-Southampton         16.25

                                                                      home_deep_completions
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                             7
                          2024-08-17 Arsenal-Wolverhampton Wanderers                     14
                          2024-08-17 Everton-Brighton                                     4
                          2024-08-17 Ipswich-Liverpool                                    2
                          2024-08-17 Newcastle United-Southampton                         4

[5 rows x 26 columns]

In [27]:
player_season_stats = understat.read_player_season_stats()
player_season_stats.head()

                                                league_id  season_id  team_id  \
league             season team    player
ENG-Premier League 2425   Arsenal Ben White             1       2024       83
                                  Bukayo Saka           1       2024       83
                                  David Raya            1       2024       83
                                  Declan Rice           1       2024       83
                                  Ethan Nwaneri         1       2024       83

                                                 player_id position  matches  \
league             season team    player
ENG-Premier League 2425   Arsenal Ben White           7298      D S       11
                                  Bukayo Saka         7322      F M       16
                                  David Raya          9676       GK       27
                                  Declan Rice         5553      M S       25
                                  Ethan Nwaneri      11132    F M S       17

                                                 minutes  goals        xg  \
league             season team    player
ENG-Premier League 2425   Arsenal Ben White          686      0  0.170845
                                  Bukayo Saka       1310      5  5.053361
                                  David Raya        2430      0       0.0
                                  Declan Rice       1987      1  1.659717
                                  Ethan Nwaneri      518      3  1.356505

                                                 np_goals     np_xg  assists  \
league             season team    player
ENG-Premier League 2425   Arsenal Ben White             0  0.170845        1
                                  Bukayo Saka           4  4.292192       10
                                  David Raya            0       0.0        0
                                  Declan Rice           1  1.659717        5
                                  Ethan Nwaneri         3  1.356505        1

                                                       xa  shots  key_passes  \
league             season team    player
ENG-Premier League 2425   Arsenal Ben White      0.411599      5           3
                                  Bukayo Saka    9.621258     46          42
                                  David Raya          0.0      0           0
                                  Declan Rice    7.866768     28          44
                                  Ethan Nwaneri  0.746519     17           8

                                                 yellow_cards  red_cards  \
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                 2          0
                                  Bukayo Saka               3          0
                                  David Raya                2          0
                                  Declan Rice               3          1
                                  Ethan Nwaneri             1          0

                                                  xg_chain  xg_buildup
league             season team    player
ENG-Premier League 2425   Arsenal Ben White       2.147624    1.995874
                                  Bukayo Saka    11.105647    4.755449
                                  David Raya      4.157595    4.157595
                                  Declan Rice    12.028125    7.513463
                                  Ethan Nwaneri   3.531674    1.984808

In [28]:
player_match_stats = understat.read_player_match_stats()
player_match_stats.head()

                                                                                      league_id  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré             1
                                                                     Alex Iwobi               1
                                                                     Andreas Pereira          1
                                                                     Antonee Robinson         1
                                                                     Bernd Leno               1

                                                                                       season_id  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré           2024
                                                                     Alex Iwobi             2024
                                                                     Andreas Pereira        2024
                                                                     Antonee Robinson       2024
                                                                     Bernd Leno             2024

                                                                                       game_id  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré        26602
                                                                     Alex Iwobi          26602
                                                                     Andreas Pereira     26602
                                                                     Antonee Robinson    26602
                                                                     Bernd Leno          26602

                                                                                       team_id  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré          228
                                                                     Alex Iwobi            228
                                                                     Andreas Pereira       228
                                                                     Antonee Robinson      228
                                                                     Bernd Leno            228

                                                                                       player_id  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré            900
                                                                     Alex Iwobi              500
                                                                     Andreas Pereira         922
                                                                     Antonee Robinson       8940
                                                                     Bernd Leno              181

                                                                                      position  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré          AMR
                                                                     Alex Iwobi            AML
                                                                     Andreas Pereira       DMC
                                                                     Antonee Robinson       DL
                                                                     Bernd Leno             GK

                                                                                       position_id  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré               11
                                                                     Alex Iwobi                 13
                                                                     Andreas Pereira             7
                                                                     Antonee Robinson            4
                                                                     Bernd Leno                  1

                                                                                       minutes  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré           79
                                                                     Alex Iwobi             90
                                                                     Andreas Pereira        90
                                                                     Antonee Robinson       90
                                                                     Bernd Leno             90

                                                                                       goals  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré          0
                                                                     Alex Iwobi            0
                                                                     Andreas Pereira       0
                                                                     Antonee Robinson      0
                                                                     Bernd Leno            0

                                                                                       own_goals  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré              0
                                                                     Alex Iwobi                0
                                                                     Andreas Pereira           0
                                                                     Antonee Robinson          0
                                                                     Bernd Leno                0

                                                                                       shots  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré          3
                                                                     Alex Iwobi            1
                                                                     Andreas Pereira       0
                                                                     Antonee Robinson      0
                                                                     Bernd Leno            0

                                                                                             xg  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré      0.114628
                                                                     Alex Iwobi        0.018718
                                                                     Andreas Pereira        0.0
                                                                     Antonee Robinson       0.0
                                                                     Bernd Leno             0.0

                                                                                       xg_chain  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré      0.136069
                                                                     Alex Iwobi        0.036473
                                                                     Andreas Pereira   0.099595
                                                                     Antonee Robinson  0.057914
                                                                     Bernd Leno        0.036473

                                                                                       xg_buildup  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré         0.02144
                                                                     Alex Iwobi          0.036473
                                                                     Andreas Pereira     0.057856
                                                                     Antonee Robinson    0.057914
                                                                     Bernd Leno          0.036473

                                                                                       assists  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré            0
                                                                     Alex Iwobi              0
                                                                     Andreas Pereira         0
                                                                     Antonee Robinson        0
                                                                     Bernd Leno              0

                                                                                             xa  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré           0.0
                                                                     Alex Iwobi             0.0
                                                                     Andreas Pereira   0.245637
                                                                     Antonee Robinson       0.0
                                                                     Bernd Leno             0.0

                                                                                       key_passes  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré               0
                                                                     Alex Iwobi                 0
                                                                     Andreas Pereira            6
                                                                     Antonee Robinson           0
                                                                     Bernd Leno                 0

                                                                                       yellow_cards  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré                 0
                                                                     Alex Iwobi                   0
                                                                     Andreas Pereira              1
                                                                     Antonee Robinson             0
                                                                     Bernd Leno                   0

                                                                                       red_cards
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré              0
                                                                     Alex Iwobi                0
                                                                     Andreas Pereira           0
                                                                     Antonee Robinson          0
                                                                     Bernd Leno                0

In [29]:
shot_events = understat.read_shot_events()
shot_events.head()

                                                                                   league_id  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré          1
                                                                     Adama Traoré          1
                                                                     Adama Traoré          1
                                                                     Alex Iwobi            1
                                                                     Calvin Bassey         1

                                                                                    season_id  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré        2024
                                                                     Adama Traoré        2024
                                                                     Adama Traoré        2024
                                                                     Alex Iwobi          2024
                                                                     Calvin Bassey       2024

                                                                                    game_id  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré     26602
                                                                     Adama Traoré     26602
                                                                     Adama Traoré     26602
                                                                     Alex Iwobi       26602
                                                                     Calvin Bassey    26602

                                                                                                  date  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré  2024-08-16 19:00:00
                                                                     Adama Traoré  2024-08-16 19:00:00
                                                                     Adama Traoré  2024-08-16 19:00:00
                                                                     Alex Iwobi    2024-08-16 19:00:00
                                                                     Calvin Bassey 2024-08-16 19:00:00

                                                                                    shot_id  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré    584627
                                                                     Adama Traoré    584644
                                                                     Adama Traoré    584645
                                                                     Alex Iwobi      584636
                                                                     Calvin Bassey   584646

                                                                                    team_id  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré       228
                                                                     Adama Traoré       228
                                                                     Adama Traoré       228
                                                                     Alex Iwobi         228
                                                                     Calvin Bassey      228

                                                                                    player_id  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré         900
                                                                     Adama Traoré         900
                                                                     Adama Traoré         900
                                                                     Alex Iwobi           500
                                                                     Calvin Bassey      11728

                                                                                    assist_player_id  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré             666195
                                                                     Adama Traoré             666191
                                                                     Adama Traoré             666190
                                                                     Alex Iwobi               666190
                                                                     Calvin Bassey            666195

                                                                                      assist_player  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré     Rodrigo Muniz
                                                                     Adama Traoré        Sasa Lukic
                                                                     Adama Traoré   Andreas Pereira
                                                                     Alex Iwobi     Andreas Pereira
                                                                     Calvin Bassey    Rodrigo Muniz

                                                                                          xg  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré   0.036473
                                                                     Adama Traoré   0.057856
                                                                     Adama Traoré   0.020298
                                                                     Alex Iwobi     0.018718
                                                                     Calvin Bassey  0.034208

                                                                                    location_x  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré        0.867
                                                                     Adama Traoré        0.809
                                                                     Adama Traoré        0.758
                                                                     Alex Iwobi          0.962
                                                                     Calvin Bassey       0.823

                                                                                    location_y  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré        0.278
                                                                     Adama Traoré        0.512
                                                                     Adama Traoré        0.361
                                                                     Alex Iwobi          0.628
                                                                     Calvin Bassey       0.572

                                                                                    minute  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré        7
                                                                     Adama Traoré       70
                                                                     Adama Traoré       71
                                                                     Alex Iwobi         47
                                                                     Calvin Bassey      75

                                                                                     body_part  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré   Right Foot
                                                                     Adama Traoré   Right Foot
                                                                     Adama Traoré   Right Foot
                                                                     Alex Iwobi           <NA>
                                                                     Calvin Bassey   Left Foot

                                                                                      situation  \
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré     Open Play
                                                                     Adama Traoré     Open Play
                                                                     Adama Traoré     Open Play
                                                                     Alex Iwobi     From Corner
                                                                     Calvin Bassey  From Corner

                                                                                          result
league             season game                                team   player
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham Fulham Adama Traoré    Missed Shot
                                                                     Adama Traoré   Blocked Shot
                                                                     Adama Traoré   Blocked Shot
                                                                     Alex Iwobi      Missed Shot
                                                                     Calvin Bassey  Blocked Shot